config/routes.rb
Sportspanda::Application.routes.draw do
  get "password_resets/new"

  resources :line_items

  get "schedule/index"

  resources :schedules

  get "sessions/new"

  get "session/new"

  get "users/new"

  get "pages/home"

  get "pages/venues"

  get "pages/events"

  get "pages/about"
  

  resources :games

  resources :sportsbars
  
  resources :users
  
  resources :sessions, :only => [:new, :create, :destroy]
     
  match '/about',       :to => 'pages#about'
  match '/contact',     :to => 'pages#contact'
  
  match '/signup',      :to => 'users#new'
  match '/signin',      :to => 'sessions#new'
  match '/signout',     :to => 'sessions#destroy'
  match '/schedule',    :to => 'schedule#index'
    
  root                  :to => 'pages#home'
  

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  
  attr_accessible :name, :email, :password, :password_confirmation, :street, :city, :state, :zip, :phone, :website, :role

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,  :presence => true,
                    :length   => { :maximum => 50 }
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
    
  has_many :games, :through => :line_items
  
  has_many :line_items
                       
  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  

  private
  
    def encrypt_password
       self.salt = make_salt if new_record?
       self.encrypted_password = encrypt(password)
     end

     def encrypt(string)
       secure_hash("#{salt}--#{string}")
     end

     def make_salt
       secure_hash("#{Time.now.utc}--#{password}")
     end

     def secure_hash(string)
       Digest::SHA2.hexdigest(string)
     end
                         
end


  

   


  
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  # GET /users
  # GET /users.xml
  def index
    @users = User.all.sort! { |a,b| a.name.downcase <=> b.name.downcase }

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])
    @title = @user.name
    @games = @user.line_items.all.sort! { |a,b| a.game.date <=> b.game.date }

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    @title = "Sign up"

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @title = "Edit User"
  end

  # POST /users
  # POST /users.xml
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end       

  # PUT /users/1
  # PUT /users/1.xml

  def update
      @user = User.find(params[:id])
      if @user.update_attributes(params[:user])
        flash[:success] = "Profile updated."
        redirect_to @user
      else
        @title = "Edit user"
        render 'edit'
      end
    end

  # DELETE /users/1
  # DELETE /users/1.xml
 
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
end

  private

    def authenticate
      deny_access unless signed_in?
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
    
   

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile:</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :Bar_Name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
	<%= f.label :Street_Address %><br />
	<%= f.text_field :street %>
  </div>
  <div class="field">
	<%= f.label :City %><br />
	<%= f.text_field :city %>
  </div>
  <div class="field">
	<%= f.label :State %><br />
	<%= f.text_field :state %>
  </div>
  <div class="field">
	<%= f.label :Zip_code %><br />
	<%= f.text_field :zip %>
  </div>
  <div class="field">
	<%= f.label :Phone_number %><br />
	<%= f.text_field :phone %>
  </div>
  <div class="field">
	<%= f.label :Website %><br />
	<%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Find out what games are showing at these sports bars:</h1>
<h4>Don't see your sports bar or venue?  <%= link_to 'Register', signup_path %> for free</h4>

<table id="users_table">
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
  
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Website</th>
  </tr>

<% @users.each do |user| %>
	<% unless user.admin? == true || user.role? == true %>
    <td><%= link_to user.name, user %></td>
    <td><%= user.street %>, <%= user.city %>, <%= user.state %>, <%= user.zip %></td>
    <td><%= number_to_phone(user.phone) %></td>
    <td><%= user.website %></td>
    <% if signed_in? && current_user.admin? %>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= button_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
   <% end %>
  </tr>
<% end %>
</table>

<script type="text/javascript">
    mixpanel.track("Venues Page Loaded")
</script>

<br>
<% if signed_in? && current_user.admin? %>
	<%= link_to 'New User', new_user_path %>
<% end %>
<br />

app/views/users/new.html.erb
<h1>Register your bar for FREE!</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :Bar_Name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
	<%= f.label :Street_Address %><br />
	<%= f.text_field :street %>
  </div>
  <div class="field">
	<%= f.label :City %><br />
	<%= f.text_field :city %>
  </div>
  <div class="field">
	<%= f.label :State %><br />
	<%= f.text_field :state %>
  </div>
  <div class="field">
	<%= f.label :Zip_code %><br />
	<%= f.text_field :zip %>
  </div>
  <div class="field">
	<%= f.label :Phone_number %><br />
	<%= f.text_field :phone %>
  </div>
  <div class="field">
	<%= f.label :Website %><br />
	<%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Register" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <b><%= @title %></b>
      </h1>
	<% unless @user.games.empty? %>
     <p>Last updated: <%= time_ago_in_words(@user.line_items.last.created_at)%> ago</p>
	<% end %>
	
	
	<% if @user.games.empty? && current_user?(@user) %>
    <br><h3>Add Games Here: </h3>
	<%= button_to 'Add Games', {:controller => "schedule", :action => "index"}, :method => :get %>
	<% else %><br><h3>Games we will be showing:</h3>
	<% end %>
	
		
		<ul>
		<% @games.each do |item| %>
		<% if item.game.date > Time.now - 21600 %>
		<li><%= item.game.name %>:
		<%= item.game.date.strftime("%a, %b %d - %I:%M %P %Z") %></li>
		<% if current_user?(@user) %>
		<%= button_to 'Remove this Game', item, :method => :delete, :class => "remove_button" %>
		<br>
		<% end %>
		<% end %>
		<% end %>
		<br />	
	
    </td>
    <td class="sidebar round">
      <strong><%= @user.name %></strong>
      <br><%= @user.street %>
	  <br><%= @user.city %>, <%= @user.state %> <%= @user.zip %>
	  <br><%= number_to_phone(@user.phone)  %>
	  <br><%= link_to @user.website, "http://#{@user.website}", :target => "_blank" %><br />
    <br>  
	<% if current_user?(@user) %>
	  <%= button_to 'Add Games', {:controller => "schedule", :action => "index"}, :method => :get %>
	  <% end %>
	<br />
    </td>
    
  </tr>
</table>

 