config/routes.rb
Sportspanda::Application.routes.draw do
  get "password_resets/new"

  resources :line_items

  get "schedule/index"

  resources :schedules

  get "sessions/new"

  get "session/new"

  get "users/new"

  get "pages/home"

  get "pages/venues"

  get "pages/events"

  get "pages/about"
  

  resources :games

  resources :sportsbars
  
  resources :users
  
  resources :sessions, :only => [:new, :create, :destroy]
     
  match '/about',       :to => 'pages#about'
  match '/contact',     :to => 'pages#contact'
  
  match '/signup',      :to => 'users#new'
  match '/signin',      :to => 'sessions#new'
  match '/signout',     :to => 'sessions#destroy'
  match '/schedule',    :to => 'schedule#index'
    
  root                  :to => 'pages#home'
  

end

app/models/sportsbar.rb
class Sportsbar < ActiveRecord::Base
  validates :name,    :presence => true
  validates :street,  :presence => true
  validates :city,    :presence => true
  validates :state,   :presence => true
  validates :zip,     :presence => true
  validates :email,   :presence => true
  
  has_and_belongs_to_many :games 
  
  has_and_belongs_to_many :users
  
end

app/controllers/sportsbars_controller.rb
class SportsbarsController < ApplicationController
  # GET /sportsbars
  # GET /sportsbars.xml
  def index
    @sportsbars = Sportsbar.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sportsbars }
    end
  end

  # GET /sportsbars/1
  # GET /sportsbars/1.xml
  def show
    @sportsbar = Sportsbar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sportsbar }
    end
  end

  # GET /sportsbars/new
  # GET /sportsbars/new.xml
  def new
    @sportsbar = Sportsbar.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sportsbar }
    end
  end

  # GET /sportsbars/1/edit
  def edit
    @sportsbar = Sportsbar.find(params[:id])
  end

  # POST /sportsbars
  # POST /sportsbars.xml
  def create
    @sportsbar = Sportsbar.new(params[:sportsbar])

    respond_to do |format|
      if @sportsbar.save
        format.html { redirect_to(@sportsbar, :notice => 'Sportsbar was successfully created.') }
        format.xml  { render :xml => @sportsbar, :status => :created, :location => @sportsbar }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sportsbar.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sportsbars/1
  # PUT /sportsbars/1.xml
  def update
    @sportsbar = Sportsbar.find(params[:id])

    respond_to do |format|
      if @sportsbar.update_attributes(params[:sportsbar])
        format.html { redirect_to(@sportsbar, :notice => 'Sportsbar was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sportsbar.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sportsbars/1
  # DELETE /sportsbars/1.xml
  def destroy
    @sportsbar = Sportsbar.find(params[:id])
    @sportsbar.destroy

    respond_to do |format|
      format.html { redirect_to(sportsbars_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sportsbars_helper.rb
module SportsbarsHelper
end

app/views/sportsbars/_form.html.erb
<%= form_for(@sportsbar) do |f| %>
  <% if @sportsbar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sportsbar.errors.count, "error") %> prohibited this sportsbar from being saved:</h2>

      <ul>
      <% @sportsbar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>



		


<% end %>

app/views/sportsbars/edit.html.erb
<h1>Editing Sports Bar</h1>

<%= render 'form' %>

<%= link_to 'Show', @sportsbar %> |
<%= link_to 'Back', sportsbars_path %> |

app/views/sportsbars/index.html.erb
<h1>Sports Bars</h1>

<table id="sportsbars_table">
  <tr>
    <th>Name</th>
    <th>Street</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sportsbars.each do |sportsbar| %>
  <tr>
    <td><%= link_to sportsbar.name, sportsbar %></td>
    <td><%= sportsbar.street %></td>
    <td><%= sportsbar.city %></td>
    <td><%= sportsbar.state %></td>
    <td><%= sportsbar.zip %></td>
    <td><%= sportsbar.email %></td>
    <td><%= sportsbar.phone %></td>
    <td><%= sportsbar.website %></td>
	<% if signed_in? && current_user.admin? %>
    <td><%= link_to 'Show', sportsbar %></td>
    <td><%= link_to 'Edit', edit_sportsbar_path(sportsbar) %></td>
    <td><%= button_to 'Destroy', sportsbar, :confirm => 'Are you sure?', :method => :delete%></td>
	<% end %>
  </tr>
<% end %>
</table>

<br>
<% if signed_in? && current_user.admin? %>
<%= link_to 'New Sportsbar', new_sportsbar_path %>
<br />
<% end %>

app/views/sportsbars/new.html.erb
<h1>New Sports Bar</h1>

<%= render 'form' %>

<%= link_to 'Back', sportsbars_path %>

app/views/sportsbars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sportsbar.name %>
</p>

<p>
  <b>Street:</b>
  <%= @sportsbar.street %>
</p>

<p>
  <b>City:</b>
  <%= @sportsbar.city %>
</p>

<p>
  <b>State:</b>
  <%= @sportsbar.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @sportsbar.zip %>
</p>

<p>
  <b>Email:</b>
  <%= @sportsbar.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @sportsbar.phone %>
</p>

<p>
  <b>Website:</b>
  <%= @sportsbar.website %>
</p>

<p>
	<b>Games that <%= @sportsbar.name%> will be showing:</b>
	<table id="profile_games">
	<% @sportsbar.games.each do |game| %>
	<tr>
		<td><%= link_to game.name, game %></td>
		<td><%= game.sport%></td>
		<td><%= game.date%></td>
	</tr>
	<% end %>
	</table>
</p>

<% if signed_in? && current_user.admin? %>
<%= link_to 'Edit', edit_sportsbar_path(@sportsbar) %> |
<%= link_to 'Back', sportsbars_path %>
<% end %>

<% if signed_in? %>
<%= link_to 'Add Games', new_game_path %>
<% end %>