config/routes.rb
Sportspanda::Application.routes.draw do
  get "password_resets/new"

  resources :line_items

  get "schedule/index"

  resources :schedules

  get "sessions/new"

  get "session/new"

  get "users/new"

  get "pages/home"

  get "pages/venues"

  get "pages/events"

  get "pages/about"
  

  resources :games

  resources :sportsbars
  
  resources :users
  
  resources :sessions, :only => [:new, :create, :destroy]
     
  match '/about',       :to => 'pages#about'
  match '/contact',     :to => 'pages#contact'
  
  match '/signup',      :to => 'users#new'
  match '/signin',      :to => 'sessions#new'
  match '/signout',     :to => 'sessions#destroy'
  match '/schedule',    :to => 'schedule#index'
    
  root                  :to => 'pages#home'
  

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
  
  validates_uniqueness_of :game_id, :scope => :user_id
  
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  
  before_filter :authenticate
  before_filter :admin_user, :only => :index
  # GET /line_items
  # GET /line_items.xml
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.xml
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.xml
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.xml
  def create
    @user = current_user
    game = Game.find(params[:game_id])
    @line_item = @user.line_items.build(:game => game)

    respond_to do |format|
      if @line_item.save
        if request.xhr?
          format.html { render :partial => "line_items/result", :locals => { :success => true } }
        else
          format.html { redirect_to(@line_item.user, :notice => 'Game added!') }
          format.xml  { render :xml => @line_item, :status => :created, :location => @line_item }
        end
      else
        if request.xhr?
          format.html { render :partial => "line_items/result", :locals => { :success => false } }
        else
          format.html { redirect_to(@line_item.user, :notice => "You've already added this game!") }
          format.xml  { render :xml => @line_item.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.xml
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to(@line_item, :notice => 'Line item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @line_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.xml
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to(@line_item.user, :notice => 'Game removed') }
      format.xml  { head :ok }
    end
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.text_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_result.html.erb
<% if success %>
<div class="result-success" style="color: green; background: transparent url(/images/success.png) no-repeat top left; padding-left: 20px">
  Game added!
</div>
<% else %>
<div class="result-fail" style="color: red; background: transparent url(/images/fail.png) no-repeat top left; padding-left: 20px">
  You've already added this game!
</div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th>Game</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.game_id %></td>
    <td><%= line_item.user_id %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Game:</b>
  <%= @line_item.game_id %>
</p>

<p>
  <b>User:</b>
  <%= @line_item.user_id %>
</p>


<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>