config/routes.rb
Sportspanda::Application.routes.draw do
  get "password_resets/new"

  resources :line_items

  get "schedule/index"

  resources :schedules

  get "sessions/new"

  get "session/new"

  get "users/new"

  get "pages/home"

  get "pages/venues"

  get "pages/events"

  get "pages/about"
  

  resources :games

  resources :sportsbars
  
  resources :users
  
  resources :sessions, :only => [:new, :create, :destroy]
     
  match '/about',       :to => 'pages#about'
  match '/contact',     :to => 'pages#contact'
  
  match '/signup',      :to => 'users#new'
  match '/signin',      :to => 'sessions#new'
  match '/signout',     :to => 'sessions#destroy'
  match '/schedule',    :to => 'schedule#index'
    
  root                  :to => 'pages#home'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="google-site-verification" content="MuyqdkB5Bd3BfEfOedi18mocXt-MLhf5Qm5Cgy2CG3Y" />
  <title>ChanneltheGame | Find Games Fast</title>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
  
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  <%= javascript_include_tag 'application' %>
  <%= favicon_link_tag 'favicon.png' %>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-25362109-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<!-- start Mixpanel --><script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==
typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);
b._i.push([a,e,d])};b.__SV=1.2}})(document,window.mixpanel||[]);
mixpanel.init("f1293e37e2989a47658008c5ff6357dd");</script><!-- end Mixpanel -->

</head>

<body>
	<div class="container">
	      <header>
	        <% logo = image_tag("logo.png", :alt => "ChanneltheGame", :class => "round") %>
			<%= link_to logo, root_path %>
	        <nav class="round">
	          <ul>
				<li><%= link_to 'Home', root_path %></li>
	            <li><%= link_to "Games", games_path %></li>
				<li><%= link_to "Sports Bars", users_path%></li>
				<% if signed_in? %>
				<li><%= link_to "My Profile", current_user %></li>
				<li><%= link_to "Settings", edit_user_path(current_user) %></li>
				<% end %>
				<% if signed_in? %>
				<li><%= link_to "Logout", signout_path, :method => :delete %></li>
				<% else %>
				<li><%= link_to "Login", signin_path %></li>
				<li><%= link_to "Sign up", signup_path, {:style=>'color:#FF0000;', :class => "css_class"} %></li>
	            <% end %>
	          </ul>
	        </nav>
	      </header>
	      <section class="round">
			 <% flash.each do |key, value| %>
		          <div class="flash <%= key %>"><%= value %></div>
		        <% end %>
	        <%= yield %>
	      </section>
	  </div>
	<script type="text/javascript" charset="utf-8">
	  var is_ssl = ("https:" == document.location.protocol);
	  var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
	  document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
	</script>

	<script type="text/javascript" charset="utf-8">
	  var feedback_widget_options = {};

	  feedback_widget_options.display = "overlay";  
	  feedback_widget_options.company = "channelthegame";
	  feedback_widget_options.placement = "left";
	  feedback_widget_options.color = "#222";
	  feedback_widget_options.style = "idea";


	  var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
	</script>
	
	<!-- Qualaroo for channelthegame.com -->
	<!-- Paste this code right after the <body> tag on every page of your site. -->
	<script type="text/javascript">var _kiq = _kiq || [];</script>
	<script type="text/javascript">
	  (function(){
	    setTimeout(function(){
	    var d = document, f = d.getElementsByTagName('script')[0], s = d.createElement('script'); s.type = 'text/javascript'; 
	    s.async = true; s.src = '//s3.amazonaws.com/ki.js/49063/a66.js'; f.parentNode.insertBefore(s, f);
	    }, 1);
	  })();
	</script>
	
	<script type="text/javascript">
	    mixpanel.track("Landing Page Loaded")
	</script>
	
</body>

<footer>
  <nav class="round">
    <ul>
	  <li><%= link_to "About", about_path %></li>
	  <li><%= link_to "Contact Us", contact_path %></li>
      <li><%= link_to "Blog", "http://channelthegame.wordpress.com", :target => "_blank" %></li>
      <li><%= link_to "Twitter", "http://twitter.com/#!/channeltgame", :target => "_blank" %></li>
	  <li><div id="fb-root"></div>
		<script src="http://connect.facebook.net/en_US/all.js#appId=193373360728625&amp;xfbml=1"></script>
		<fb:like href="www.channelthegame.com" send="true" layout="button_count" width="150" show_faces="false" font=""></fb:like></li>
	
	<li><div id="plusone">
	<g:plusone size="small" annotation="inline" width="400"></g:plusone>

	<!-- Place this render call where appropriate -->
	<script type="text/javascript">
	  (function() {
	    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
	    po.src = 'https://apis.google.com/js/plusone.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
	  })();
	</script></li></div>
    </ul>
  </nav>
</footer>


</html>